#!/usr/bin/env bash
# Configures your Nginx server so that /redirect_me redirects to another page.
# The redirection must be a “301 Moved Permanently”
STRING="Hello World!"
REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=2bI8XsdNb-c&list=PLVipAi3U-Jos-gFKT434UTj2D9x7t83IH; \n\t}\n"
FILE="/etc/nginx/sites-available/default"
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "$STRING" > /var/www/html/index.nginx-debian.html
sed -i "37i\ $REDIRECT" "$FILE"
service nginx restart
